### PR TITLE
added QueueGetConfigReply

### PR DESCRIPTION
**Pull request by ksang**
Added QueueGetConfigReply message to openflow of10.
Also runned go fmt.

### CODE REVIEW

**Comment by superkkt** [comment]
@ksang Thank you for your valuable patch, but I think it should be also implemented in OF1.3. Could you add it into OF1.3's queue as well? In addition, it seems that ```QueueID()``` name is trivial. What do you think to change it from ```QueueID()``` to ```ID()```?

**Comment by ksang** [comment]
@superkkt Thanks, I've updated pull request, please check.

**Comment by superkkt** [comment]
@ksang Thanks. IMHO, we need a discussion to modify following issues:

1. ```uint32``` is enough for the return type of ```QueueGetConfigReply.Port()```. ```openflow.OutPort``` is for a logical packet output port specification. 

2. We have to prepare that ```ofp_queue_properties``` is ```OFPQT_NONE``` in OF10. ```OFPQT_NONE``` means _"No property defined for queue (default)"_, so I guess a switch may send a reply with ```OFPQT_NONE``` if it does not have any queue properties. How about to capture ```openflow.ErrUnsupportedProperty``` error at ```cherryd/openflow/of10/queue.go:125```, and then skip adding the unmarshaled queue into the queue slice.

3. ```openflow.Queue``` interface should have maxRate as well because OF13 has it.

4. The routines for OF13 have to be reimplemented in order to fit the OF13 protocol. This is because OF13 has additional queue properties (i.e., maxRate), and it seems that OF13 allows ```ofp_packet_queue``` structure consists of headers only (no property) as there is no ```OFPQT_NONE``` value in OF13. So, unlike OF10, I think the length of ```ofp_packet_queue``` structure may vary depending on the number of its properties.

Please let me know your opinion.

**Comment by ksang** [comment]
@superkkt Thank you for pointing out those stuffs.

- 1. I totally agree, `OutPort `is good for setting Port value but unnecessary for getting the value.
- 2 - 4. Sorry, the specification I referenced is http://flowgrammable.org/sdn/openflow/message-layer/queue/#ofp_1_0, which is a little bit misleading. In this case I think maybe we need a `QueueProperty `interface and a enum type `PropertyType`.

I propose something like this:

```
openflow/queue.go:
type PropertyType uint16
const (
    OFPQT_NONE PropertyType = iota
    OFPQT_MIN_RATE
    OFPQT_MAX_RATE
    OFPQT_EXPERIMENTER     = 0xffff
)

type QueueProperty interface {
    Type() PropertyType 
    Length() uint16
    Rate() (uint16, error) // return an error if the type is not rate related.
    Experimenter() (uint32, error) // return an error is it is not experimenter property
    Data() []byte
}

type Queue interface {
    ID() uint32
    Length() uint16
    Property []QueueProperty
}

```

Thanks

**Comment by superkkt** [comment]
@ksang Very nice! I agree with your proposal.

**Comment by ksang** [comment]
@superkkt Done, please review.

**Comment by superkkt** [comment]
@ksang Nice! However, I have found a small mistake at _cherryd/openflow/of13/queue.go:118_. I think ```r.data``` should be allocated before that line. Otherwise, the experimenter data will not be copied into ```r.data``` as _the number of elements copied is the minimum of len(src) and len(dst)_. I believe we could finish this PR after that modification! :-) Thanks.

**Comment by ksang** [comment]
@superkkt Thanks for pointing this bug out, I've added size allocation for `r.data`

**Comment by superkkt** [comment]
@ksang Merged! Many thanks for your efforts. 

By the way, do you mind if I ask a personal question? Actually, I live in Korea and sometimes go to Japan for business. I guess you are Japanese due to your first name, am I right? Do you live in Japan?

**Comment by ksang** [comment]
@superkkt lol. I'm living in Shanghai right now. I'm a Japanese culture fan and have been there many times. Nice to meet you :D

**Comment by ksang** [comment]
@superkkt It's so kind of you :). The opportunity looks very attractive, however I just moved to a new company so don't have a plan to change again at this moment. Thanks again.

**Comment by superkkt** [comment]
@ksang Okay. Please do not hesitate to contact me if you are interested at anytime later. Here is the my LinkedIn profile: http://kr.linkedin.com/in/superkkt

**Pull request merged**
